routes:
  - virtual-address: gatway.service
    max-conn: 3000
    max-idle-conn: 32
    max-idle-timeout-minute: 30
    rules:
      - 1
    endpoints:
      - laddr: 0.0.0.0:10001
        vaddr: Gateway@0.0.0.0:10000
    commands:
      - OnRequestGatewayCloseClient
      - OnRequestGatewayAlterRule
      
  - virtual-address: battle.service
    max-conn: 3000
    max-idle-conn: 32
    max-idle-timeout-minute: 30
    rules:
      - 3
    endpoints:
      - laddr: 0.0.0.0:10200
        vaddr: Battle@0.0.0.0:10200
    commands:
      - OnRequestExitBattleSpace,2000