routes:
  - virtual-address: gatway.service
    max-idle-conn: 1024
    max-idle-timeout-minute: 30
    max-idle-conn-timeout-second: 2
    kleepalive-millisec: 2000
    endpoints:
      - laddr: 0.0.0.0:10001
        vaddr: Gateway@0.0.0.0:10000
    commands:
      - prvs.RequestGatewayCloseClient
      - prvs.RequestGatewayAlterRule
    rules:
      - 1
  - virtual-address: battle.service
    max-idle-conn: 1024
    max-idle-timeout-minute: 30
    max-idle-conn-timeout-second: 2
    kleepalive-millisec: 2000
    endpoints:
      - laddr: 0.0.0.0:10200
        vaddr: Battle@0.0.0.0:10200
    commands:
      - prvs.RequestExitBattleSpace,2000
    rules:
      - 1