routes:
  - virtual-address: gatway.service
    max-conn: 3000
    max-idle-conn: 32
    max-idle-timeout-minute: 30
    rules:
      - 3
    endpoints:
      - laddr: 0.0.0.0:10001
        vaddr: Gateway@0.0.0.0:10000
    commands:
      - prvs.RequestGatewayCloseClient
      - prvs.RequestExitBattleSpace
