routes:
  - virtual-address: gatway.service
    max-idle-conn: 1024
    max-idle-timeout-minute: 30
    max-idle-conn-timeout-second: 2
    kleepalive-millisec: 4000
    endpoints:
      - laddr: 0.0.0.0:8801
        vaddr: 0.0.0.0:8801
    commands:
      - prvs.RequestGatewayCloseClient
    rules:
      - 1