server:
  laddr: 0.0.0.0:8800
  laddr_servant: 0.0.0.0:8801
  vaddr: 0.0.0.0:8800
  encryption-enabled: false
  online-number: 5000
  request-timeout-max: 2000
router:
  uri: routes.yaml
  algorithm: p2c
log_remote_addr: 0.0.0.0:9092
    
