routes:
  - virtual-address: 172.171.24.12:6666
    max-idle-conn: 1024
    max-idle-timeout-minute: 30
    max-idle-conn-timeout-second: 2
    kleepalive-millisec: 4000
    endpoints:
      - "127.0.0.1:8860"
    commands:
      - protocols.SigninRequest
      - protocols.SignoutRequest
    rules:
      - 1